name: Update Version File
on:
    push:
        branches:
            - main

jobs:
    update:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Create Version File
              run: echo "${{ github.sha }}" > version.txt

            - name: Commit and Push Version File
              uses: EndBug/add-and-commit@v9
              with:
                  message: 'Auto-update version.txt [skip ci]'
                  add: 'version.txt'
