name: Send ZIP to Discord

on:
    workflow_dispatch:

jobs:
    send-zip:
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Create ZIP
              shell: bash
              run: |
                  set -euo pipefail
                  zip -r V5.zip . \
                    -x ".git/*" \
                       ".github/*" \
                       ".vscode/*" \
                       "README.md" \
                       ".gitignore"

            - name: Send ZIP to Discord
              shell: bash
              env:
                  WEBHOOK: ${{ secrets.PUSH_NOTIFIER }}
              run: |
                  set -euo pipefail

                  curl -sS --fail-with-body \
                    -F "files[0]=@V5.zip;filename=V5.zip" \
                    "$WEBHOOK"
